services:
  fshare-backend:
    build:
      context: ./fshare-backend
      target: development
    volumes:
      - ./fshare-backend:/app
      - ./public:/public
    user: "${UID}:${GID}"

  fshare-web:
    build:
      context: ./fshare-web
      target: development
    volumes:
      - ./fshare-web:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"