services:

  fshare-backend:
    build:
      context: ./fshare-backend
      target: production
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - /home/fshare/public:/public

  fshare-web:
    build:
      context: ./fshare-web
      target: production
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - fshare-backend
      - fshare-web

volumes:
  caddy-data:
  caddy-config: