services:
  fshare-backend:
    network_mode: host
    build:
      context: ./fshare-backend
      target: development
    volumes:
      - ./fshare-backend:/app
      - ./public:/public
    user: "${UserID}:${GroupID}"

  fshare-web:
    network_mode: host
    build:
      context: ./fshare-web
      target: development
    environment:
      VITE_API_URL: http://localhost:9300  
    volumes:
      - ./fshare-web:/app
      # - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"