services:

  fshare-backend:
    build:
      context: ./fshare-backend
      target: production
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - /home/fshare/public:/public
    depends_on: redis
  redis:
    image: redis:latest
    restart: unless-stopped

  caddy:
    build:
        context: ./fshare-web
        target: production
    image: fshare-caddy:latest
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - fshare-backend

volumes:
  caddy-data:
  caddy-config: