[package]
name = "fshare-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "*", features = ["full"]}
axum = "*"
uuid = {version = "*", features = ["v4","serde"]}
anyhow = "*"
axum-anyhow = "*"
local-ip-address = "0.6.13"
serde = {version="*", features = ["derive"]}
ctrlc = "3.5.2"
mime_guess = "2.0.5"
